//file:noinspection GroovyAssignabilityCheck
import io.github.fvarrui.javapackager.model.FileAssociation

plugins {
    id 'application'
    id 'org.springframework.boot' version '4.1.0-M2'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'io.github.fvarrui.javapackager.plugin' version '1.7.6'
}

var applicationName = 'basalt'
base.archivesName = applicationName

dependencies {
    implementation 'org.dyn4j:dyn4j:5.0.2'
    implementation 'net.sf.doolin:javadocking:1.4.2'
    implementation 'org.commonmark:commonmark:0.27.1'
    implementation 'com.formdev:flatlaf:3.7'
    implementation 'com.formdev:flatlaf-intellij-themes:3.7'

    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.data:spring-data-commons'

    implementation project(':share')
    implementation project(':server')
}

application {
    mainClass = 'org.gershaveut.basalt.Application'
}

javapackager {
    mainClass = 'org.gershaveut.basalt.Application'
    customizedJre = false
    bundleJre = true
    platform = 'auto'

    name = applicationName

    fileAssociations = [
           new FileAssociation().tap {
               mimeType = 'application/x-basalt'
               extension = 'basalt'
               description = 'basalt'
           }
    ]
    
    linuxConfig {
        generateDeb = false
        generateRpm = false
    }

    winConfig {
        generateMsi = false
    }

    macConfig {
        generatePkg = false
    }
}
