plugins {
    id 'java'
}

group = 'dev.code_offline'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'org.dyn4j:dyn4j:5.0.2'
    implementation 'net.sf.doolin:javadocking:1.4.2'
    implementation 'org.xerial:sqlite-jdbc:3.49.1.0'
}

test {
    useJUnitPlatform()
}