subprojects {
    apply plugin: 'java'

    group = 'dev.code_offline'
    version = '0.4'

    repositories {
        mavenCentral()
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    dependencies {
        implementation platform("org.springframework.boot:spring-boot-dependencies:4.0.0")
    }
}
