subprojects {
    apply plugin: 'java'

    group = 'org.gershaveut'
    version = '0.4'

    repositories {
        mavenCentral()
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    dependencies {
        implementation platform("org.springframework.boot:spring-boot-dependencies:4.1.0-M2")
    }
}
