spring.application.name=basalt-server
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:./basalt
spring.datasource.username=code-offline
spring.datasource.password=offline

spring.jpa.hibernate.ddl-auto=update