spring.datasource.username=database
spring.datasource.password=database

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.check_nullability=true

spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB

server.error.include-stacktrace=never
server.port=7600
server.ssl.key-store-password=certificate
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=certificate