plugins {
    id 'java'
    id 'application'
    id 'org.springframework.boot' version '3.5.7'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'io.github.fvarrui.javapackager.plugin' version '1.7.6'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.dyn4j:dyn4j:5.0.2'
    implementation 'net.sf.doolin:javadocking:1.4.2'
    implementation 'org.commonmark:commonmark:0.27.0'
    implementation 'org.checkerframework:checker-qual:3.51.1'
    implementation 'com.google.code.gson:gson:2.13.2'

    implementation 'org.springframework.boot:spring-boot-starter-webflux:3.5.6'

    implementation project(":server")
}

application {
    mainClass = 'dev.code_offline.basalt.Main';
}

javapackager {
    mainClass = 'dev.code_offline.basalt.Main'
    bundleJre = true
    platform = 'auto'
}
