plugins {
    id 'java'
    id 'application'
    id 'org.springframework.boot' version '3.3.4'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'dev.code_offline'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.dyn4j:dyn4j:5.0.2'
    implementation 'net.sf.doolin:javadocking:1.4.2'
    implementation 'org.commonmark:commonmark:0.24.0'
    implementation 'org.checkerframework:checker-qual:3.49.2'
    implementation 'com.google.code.gson:gson:2.12.1'

    implementation 'org.springframework.boot:spring-boot-starter-hateoas:3.4.4'
    implementation 'org.springframework.boot:spring-boot-starter-webflux:3.4.4'

    implementation project(":server")
}

application {
    mainClass = 'dev.code_offline.basalt.Main';
}

test {
    useJUnitPlatform()
}