plugins {
	id 'java'
	id 'application'
	id 'org.springframework.boot' version '3.5.7'
	id 'io.spring.dependency-management' version '1.1.7'
}

archivesBaseName = 'basalt-server'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
}

application {
	mainClass = 'dev.code_offline.basalt_server.BasaltApplication'
}
